Razor/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace Razor.Models
{
    public class Employee
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [MinLength(3)]
        public string Name { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$",
        ErrorMessage = "Invalid email format")]
        public string Email { get; set; }

        public string PhotoPath { get; set; }

        [Required]
        public Dept? Department { get; set; }
    }
}

Razor/Pages/Employees/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Razor.Models;
using Razor.Services;

namespace Razor.Pages.Employees
{
    public class DeleteModel : PageModel
    {

        private readonly ILogger<EditModel> _logger;
        private readonly IEmployeeRepository employeeRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public DeleteModel(ILogger<EditModel> logger, IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
        {
            _logger = logger;
            this.employeeRepository = employeeRepository;
            this.webHostEnvironment = webHostEnvironment;
        }


        [BindProperty]
        public Employee Employee { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        public IActionResult OnGet()
        {
            Employee = employeeRepository.GetEmployee(Id);
            if (Employee == null)
            {
                return RedirectToPage("/NotFound");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            Employee  deletedEmployee = employeeRepository.Delete(Employee.Id);
            if (deletedEmployee == null)
            {
                return RedirectToPage("/NotFound");
            }
            return RedirectToPage("Index");
        }
    }
}

Razor/Pages/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Razor.Models;
using Razor.Data;
using Razor.Services;

namespace Razor.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly ILogger<DetailsModel> _logger;
        private readonly IEmployeeRepository employeeRepository;
        public DetailsModel(ILogger<DetailsModel> logger, IEmployeeRepository employeeRepository)
        {
            _logger = logger;
            this.employeeRepository = employeeRepository;
        }
        public Employee Employee { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [TempData]
        public string Message { get; set; }

        public IActionResult OnGet()
        {
            Employee = employeeRepository.GetEmployee(Id);
            if (Employee == null)
            {
                return RedirectToPage("/NotFound");
            }
            return Page();
        }
    }
}

Razor/Pages/Employees/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Razor.Models;
using Razor.Data;
using Razor.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace Razor.Pages
{
    public class EditModel : PageModel
    {
        private readonly ILogger<EditModel> _logger;
        private readonly IEmployeeRepository employeeRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EditModel(ILogger<EditModel> logger, IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
        {
            _logger = logger;
            this.employeeRepository = employeeRepository;
            this.webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Employee Employee { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? Id { get; set; }

        [BindProperty]
        public IFormFile Photo { get; set; }

        [BindProperty]
        public bool Notify { get; set; }

        public string Message { get; set; }

        public IActionResult OnGet()
        {
            if (Id.HasValue)
            {
                Employee = employeeRepository.GetEmployee((int)Id);
            }
            else
            {
                Employee = new Employee();
            }

            if (Employee == null)
            {
                return RedirectToPage("/NotFound");
            }
            return Page();
        }

        public IActionResult OnPostUpdateNotificationPreferences()
        {
            if (Notify)
            {
                Message = "Thank you for turning on notifications";
            }
            else
            {
                Message = "You have turned off email notifications";
            }

            TempData["message"] = Message;
            return RedirectToPage("/Employees/Details", new { id = Id });
        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    if (Employee.PhotoPath != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath, "images", Employee.PhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    Employee.PhotoPath = ProcessUploadedFile();
                }

                if (Employee.Id > 0)
                {
                    Employee = employeeRepository.Update(Employee);
                }
                else
                {
                    Employee = employeeRepository.Add(Employee);
                }
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }

        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;
            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }


    }
}

Razor/Pages/Employees/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Razor.Models;
using Razor.Data;
using Razor.Services;

namespace Razor.Page
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IEmployeeRepository employeeRepository;
        public IndexModel(ILogger<IndexModel> logger, IEmployeeRepository employeeRepository)
        {
            _logger = logger;
            this.employeeRepository = employeeRepository;
        }
        public IEnumerable<Employee> Employees { get; set; }
        public void OnGet()
        {

            Employees = employeeRepository.GetAllEmployees();
        }

    }
}

Razor/Pages/Employees/Delete.cshtml
@page "{id:min(1)}"
@model Razor.Pages.Employees.DeleteModel
@{
    ViewData["Title"] = "Delete";
    ViewData["ShowButtons"] = false;
}
<h1>@ViewData["Title"] Confirmation</h1>

<div class="alert alert-danger">
    <partial name="_displayEmployeePartial" model="Model.Employee" view-data="ViewData"></partial>
    <h5>Are you sure you want to delete employee - @Model.Employee.Name</h5>
    <form method="POST">
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a class="btn btn-primary" asp-page="/Employees/Index">No, Cancel</a>
    </form>
</div>

Razor/Pages/Employees/Details.cshtml
@page "/Employee/View/{id:min(1)}"
@model Razor.Pages.DetailsModel
@{
    ViewData["Title"] = "Details";
    var photoPath = "~/images/" + (Model.Employee.PhotoPath ?? "ad1.png");
}
<h1>@ViewData["Title"]</h1>

<div class="row justify-content-center m-3">
    @if (Model.Message != null)
    {
        <div class="col-sm-8">
            <div class="alert alert-primary">
                @Model.Message
            </div>
        </div>
    }
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.Employee.Name</h1>
            </div>

            <div class="card-body text-center">
                <img class="card-img-top" src="@photoPath" asp-append-version="true" />

                <h4>Employee ID : @Model.Employee.Id</h4>
                <h4>Email : @Model.Employee.Email</h4>
                <h4>Department : @Model.Employee.Department</h4>

            </div>
            <div class="card-footer text-center">
                <a asp-page="index"
                   class="btn btn-primary">Back</a>
                <a asp-page="/Employees/Edit" asp-route-id="@Model.Employee.Id"
                   class="btn btn-primary">Edit</a>
                <a href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

Razor/Pages/Employees/Edit.cshtml
@page "{id:min(1)?}/{handler?}"
@model Razor.Pages.EditModel
@{
    ViewData["Title"] = "Edit";
    var photoPath = "~/images/" + (Model.Employee.PhotoPath ?? "ad1.png");
    var pageHeader = Model.Employee.Id > 0 ? "Edit" : "Create";
}
<h2>Notification Preferences</h2>

<form method="post" asp-page-handler="UpdateNotificationPreferences">
    <div class="form-check">
        <input asp-for="Notify" class="form-check-input" />
        <label asp-for="Notify" class="form-check-label">
            Receive email notification when my details change
        </label>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">
        Update Notification Preferences
    </button>
</form>

<hr>
<h2>@pageHeader</h2>

<form method="post" class="mt-3" enctype="multipart/form-data"  asp-page-handler="OnPost">
    @*Use hidden input elements to store employee id which
        we need when we submit the form*@
    <input hidden asp-for="Employee.Id" />
    <input hidden asp-for="Employee.PhotoPath" />

    @*asp-for tag helper takes care of displaying the existing
        data in the respective input elements*@
    <div class="form-group row">
        <label asp-for="Employee.Name" class="col-sm-2 col-form-label">
        </label>
        <div class="col-sm-10">
            <input asp-for="Employee.Name" class="form-control" placeholder="Name">
            <span asp-validation-for="Employee.Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Employee.Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Employee.Email" class="form-control" placeholder="Email">
            <span asp-validation-for="Employee.Email" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Employee.Department" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="Employee.Department" class="custom-select mr-sm-2"
                asp-items="Html.GetEnumSelectList<Dept>()">
                <option value="">Please Select</option>
            </select>
            <span asp-validation-for="Employee.Department" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input asp-for="Photo" class="custom-file-input form-control">
                <label class="custom-file-label">Click here to change photo</label>
            </div>
        </div>
    </div>
    <div class="form-group row col-sm-4 offset-4">
        <img class="imageThumbnail" src="@photoPath" alt="Photo" asp-append-version="true" />
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-page="/Employees/Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>
    @section Scripts{
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>
    <partial name="_ValidationScriptsPartial"></partial>
    }
</form>

Razor/Pages/Employees/Index.cshtml
@page 
@model Razor.Page.IndexModel
@{
    ViewData["Title"] = "Employees";
    ViewData["ShowButtons"] = true;
}
<h1>Employees</h1>
<div class="card-deck">
    @foreach (var employee in Model.Employees)
    {
        <partial name="_displayEmployeePartial" model="employee" view-data="ViewData"></partial>
    }
</div>